### ISSUE TITLE
level data lost 

### ISSUE THREAD

**Issue by SaviorDT** [EbonJaeger/perworldinventory-kt#109]
**Describe the bug**
When my players died, their levels lost, only the xp remain. If op died, levels remain. Didn't I give some permission to players?

**To Reproduce**
1. give me 100L and deop my self
2. suicede
3. my level all lost
4. Can't find error

**Expected behavior**
I want not to drop levels when i died.

**Plugin version**
- [ ] Using the `legacy` jar
I use v2.1.0

**Server version**
v1.12.2
Spigot 1.12.2 #131

**Additional context and logs**
05.01 08:24:21 [Server] INFO Savior_DT issued server command: /suicide
05.01 08:24:21 [Server] INFO [FINE] ProfileManager: Saving player 'Savior_DT' to database
05.01 08:24:21 [Server] INFO [DEBUG] ProfileManager: Key is: ProfileKey{uuid='5cffb9b7-4f54-4e1e-9b2e-7d523ecae529', group='all', gameMode='survival'}
05.01 08:24:21 [Server] INFO Savior_DT died
05.01 08:24:21 [Server] INFO [FINE] Saving data for player '《冒險者》~Savior_87'
05.01 08:24:21 [Server] INFO [DEBUG] Data being saved in file 'plugins/PerWorldInventory/data/5cffb9b7-4f54-4e1e-9b2e-7d523ecae529/all.json'
05.01 08:24:21 [Server] INFO [FINE] Writing player data for player '《冒險者》~Savior_87' to file
05.01 08:24:21 [Server] INFO [DEBUG] [SERIALIZER] Serializing player '《冒險者》~Savior_87'
05.01 08:24:21 [Server] INFO [DEBUG] [SERIALIZER] Done serializing player '《冒險者》~Savior_87'

**Comment by Oruss7** [comment]
Hello, 
Get the same issue.
Version: kt-2.2.2
Spigot: 1.13.2 (latest 13/07/19)

**Comment by Oruss7** [comment]
kt-2.3.1: still occurs

**Comment by Oruss7** [comment]
PWI use `if (!event.keepLevel)` but this value is not used anymore since 1.8:
https://hub.spigotmc.org/jira/browse/SPIGOT-2222
