### ISSUE TITLE
Server creating a [WARN]

### ISSUE THREAD

**Issue by CMCosMic** [EbonJaeger/perworldinventory-kt#116]
I am running Minecraft 1.12.2 and using PWI 2.2.2
Here is the full config - [link](https://pastebin.com/bJYZPeke)
Here is the [WARN] - [link](https://pastebin.com/RxeSab2Z)

Basically the Issue is that its giving a WARN and I just want to make sure its safe to go on since I dont want to loose all my stuff, since its happened before.

**Comment by EbonJaeger** [comment]
Please post the contents of your `worlds.yml` file; that error indicates that it's messed up.

On an unrelated note, you should be using the legacy jar from the GitHub Releases page on server versions older than 1.13.

**Comment by CMCosMic** [comment]
worlds.yml- 
`# # In this file you define your groups and the worlds in them.
# # Follow this format:
# # groups:
# #   default:
# #     worlds:
# #     - world
# #     - world_nether
# #     - world_the_end
# #     default-gamemode: SURVIVAL
# #   creative:
# #     worlds:
# #     - creative
# #     default-gamemode: CREATIVE
# #
# # 'default' and 'creative' are the names of the groups
# # worlds: is a list of all worlds in the group
# # If you have 'manage-gamemodes' set to true in the main config, the server
# # will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
  hub:
    worlds:
    - hub
    - hub_nether
    - hub_the_end
    default-gamemode: SURVIVAL
  world:
    worlds:
    - world
    - world_nether
    - world_the_end
    - explore
    default-gamemode: SURVIVAL
  skyblock:
    - skyblock
    - skyblock_nether
	`
And  I changed to v2.0.1 but the issue is still happening.

**Comment by EbonJaeger** [comment]
@CMCosMic your worlds configuration is broken. Your `skyblock` world is missing the `worlds:` line in it.

**Comment by EbonJaeger** [comment]
Closing due to lack of response.
