### ISSUE TITLE
EXP reset bug

### ISSUE THREAD

**Issue by ZwingGX** [EbonJaeger/perworldinventory-kt#120]
There's a bug that the EXP disappears.

1. type "/gamerule keepInventory true"
2. Set players Exp (any count)
4. Player die (not have bypass permission)
5. Exp reset

**Plugin version**
perworldinventory-kt-2.2.2

**Server version**
paper 1.12.2

**Comment by Oruss7** [comment]
duplicate https://github.com/EbonJaeger/perworldinventory-kt/issues/109
