### ISSUE TITLE
Error perworldinventory-kt-2.0.1.jar -> perworldinventory-kt-2.2.2.jar

### ISSUE THREAD

**Issue by account111account** [EbonJaeger/perworldinventory-kt#134]
**Describe the bug**
There is a error in the console but otherwise no, nothing

**To Reproduce**
Update from perworldinventory-kt-2.0.1.jar to perworldinventory-kt-2.2.2.jar

**Expected behavior**
The error should go away

**Plugin version**
- [x] Using the latest released version of the plugin
- [ ] Using the `legacy` jar

**Server version**
Spigot 1.13.2

**Additional context and logs**
https://pastebin.com/f4fsPxFb

**Comment by EbonJaeger** [comment]
Well, you managed to cut out the actual error there. Can you try that again, please?

**Comment by account111account** [comment]
That was the full error

**Comment by account111account** [comment]
28.04 18:59:04 [Server] INFO org.bukkit.event.EventException: null

28.04 18:59:04 [Server] ERROR Could not pass event PlayerSpawnLocationEvent to PerWorldInventory v2.2.2

**Comment by account111account** [comment]
@EbonJaeger Can you help me?

**Comment by EbonJaeger** [comment]
Should be fixed in the upcoming 1.14 version.
Ref #114 
Duplicate of #94 and #111
