### ISSUE TITLE
Error spam when player logs in to the server.

### ISSUE THREAD

**Issue by t0xic1** [EbonJaeger/perworldinventory-kt#136]
**Describe the bug**
When a player logs in this error occurs.

**To Reproduce**
1. start a 1.13.2 spigot server
2. log in with your account

**Expected behavior**
An error will appear in console.

**Plugin version**
- [x] PerWorldInventory 2.2.2

**Server version**
Spigot 1.13.2

**Additional context and logs**
https://pastebin.com/HDNCGGUK

**Comment by EbonJaeger** [comment]
Fixed in upcoming version.
