### ISSUE TITLE
Inventory didn't transfer 1.14.2

### ISSUE THREAD

**Issue by kaniesha** [EbonJaeger/perworldinventory-kt#140]
**Describe the bug**
Earlier tonight, when teleporting from one world to another using cmi sethomes, my inventory didn't switch back from when I was previously in survival mode.

**To Reproduce**
1. Switch to another world that is set to creative only
2. Switch back to another world that is survival by default, but allows creative
4. Missing inventory

**Expected behavior**
I expected my previous survival inventory to be present as it usually is.

**Plugin version**
- [x] Using the latest released version of the plugin
- [ ] Using the `legacy` jar

**Server version**
1.14.2

**Additional context and logs**
Error when my inventory wasn't switched back:
https://hastebin.com/davaloduwe.sql

Another error shortly after:
https://hastebin.com/xucinuxupe.sql

**Comment by kaniesha** [comment]
Oh, I'm sorry about that. I didn't realize that hastebin really meant haste.
https://pastebin.com/NFR9vwDe
https://pastebin.com/a7uKTYqj

I'm not sure how to get to a log longer than that, these are the logs directly from the logs folder on the server.

**Comment by EbonJaeger** [comment]
Sort of a lie; there are two separate errors in this report, so it's only half-closed.

**Comment by EbonJaeger** [comment]
Actually... That might fix both of them. @kaniesha could you try this file and see if that is correct? DON'T unzip it, just rename it to end in .jar.
[perworldinventory-kt-2.3.0.zip](https://github.com/EbonJaeger/perworldinventory-kt/files/3229709/perworldinventory-kt-2.3.0.zip)

**Comment by EbonJaeger** [comment]
@TheoRetisch1 Could you see if this fixes your problem as well?

**Comment by mercurialmusic** [comment]
Getting the same, possibly, also using CMI. I posted it there as well.

Getting a pretty big glitch (spam and inventory wipe) with the new PerWorldInventory and CMI. Leaving this in both places since it only happens when using the CMI gamemode commands. I don't get the error when using, e.g.: /minecraft:gamemode creative.

https://gist.github.com/mercurialmusic/5ce8d66ddcc073d77fa2d6fbb4063877

**Server Version:** 
CraftBukkit version git-Spigot-f09662d-3697519 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
**Relevant plugins:** 
PerWorldInventory 2.3.0
CMI 8.6.4.0

**Comment by EbonJaeger** [comment]
@mercurialmusic Blame for this one falls on me, I'm afraid. Can you please try the file I attached a couple of comments up and tell me if that resolves the issue?

**Comment by mercurialmusic** [comment]
Cool. Yes, will try, and thank you.

**Comment by EbonJaeger** [comment]
Forgot to say it earlier, but it happens because of how potion effects are handled.

**Comment by kaniesha** [comment]
Another player had the same thing happen to him last night but didn't notice it until today when he switched out of creative mode.

https://gist.github.com/kaniesha/580e65623c96ec2e4597203685c7fcb4

**Comment by mercurialmusic** [comment]
The fix is still messing inventories for me, especially creative > survival.

**Comment by AngieC233** [comment]
Having same issues with survival inventory and ender chest inventory wiped from players when going back from PlotWorld (Creative) to Survival.  Errors spamming console when using EssentialX commands like /home and even /spawn...

**Server Version:**
This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Relevant plugins:**
PerWorldInventory 2.3.0
EssentialX-2.16.1.150

[https://pastebin.com/YAjHVW8e](url)

**Comment by EbonJaeger** [comment]
@AngieC233 Have you tried the attached file I posted a few comments above? I'm not getting these errors using it.

**Comment by AngieC233** [comment]
> @AngieC233 Have you tried the attached file I posted a few comments above? I'm not getting these errors using it.

Sorry didn't realised it can't be access.  I re-attached it, should be able to access those info now

**Comment by EbonJaeger** [comment]
@AngieC233 nono, I meant my comment above that has a new version of the plugin jar file.

**Comment by kaniesha** [comment]
I forgot to mention in my latest comment that I am using the newest jar you attached in the thread. A third player had the problem (with the new jar as well):
https://gist.github.com/kaniesha/bce7ba676de6e707a1b45d454a21f70d

**Comment by EbonJaeger** [comment]
You are sure that you renamed the file to end in .jar, and removed the old version, and restarted the server? I am unable to cause the error using this version.

**Comment by kaniesha** [comment]
Yes. Would the plugin/I need to rewrite the config files?

**Comment by EbonJaeger** [comment]
You shouldn't. Could you provide me with the data file(s) for a player currently having this problem?

**Comment by kaniesha** [comment]
As far as I know, it's only happening to staff members. Myself, and two other op-ed admins. This should be my player data (the dat file, yes?), it needs to be unzipped.

[39b765fe-583f-44cb-be1f-4e97c6fef9e9.zip](https://github.com/EbonJaeger/perworldinventory-kt/files/3238974/39b765fe-583f-44cb-be1f-4e97c6fef9e9.zip)

**Comment by EbonJaeger** [comment]
Sorry, I should have been more clear. I meant the PWI data files located in `plugins/PerWorldInventory/data/<player's_uuid>/`.

**Comment by kaniesha** [comment]
Oh, gotcha. Here's mine.
[pwi user data.zip](https://github.com/EbonJaeger/perworldinventory-kt/files/3238981/pwi.user.data.zip)

**Comment by EbonJaeger** [comment]
As I figured, everything is normal there. I'm pretty sure I didn't upload the wrong file before, but just in case, here it is with the version string changed, just to rule that out. As I said, I cannot reproduce this problem with PotionEffects.
[perworldinventory-kt-2.3.0a.zip](https://github.com/EbonJaeger/perworldinventory-kt/files/3239015/perworldinventory-kt-2.3.0a.zip)

**Comment by kaniesha** [comment]
Alright, sorry this is being so difficult. I'm kind of chalking up all of our server issues to CMI not updating for 1.14.2 yet, honestly.

**Comment by mercurialmusic** [comment]
@kaniesha I'm still on 1.13.2 and having the same issue, so I don't think it's that. 

And @EbonJaeger I was also still having the issue with the first fix. I'll try this new one as well.

**Comment by mercurialmusic** [comment]
This new build seems to have fixed it for me :) Thanks!

**Comment by EbonJaeger** [comment]
You are sure that you renamed the file to end in .jar, and removed the old version, and restarted the server? I am unable to cause the error using this version.

Sent from Mail for Windows 10

**Comment by EbonJaeger** [comment]
You are sure that you renamed the file to end in .jar, and removed the old version, and restarted the server? I am unable to cause the error using this version.

Sent from Mail for Windows 10

**Comment by liamcullins** [comment]
Ops on our server are having the same issue. We're running Spigot version git-Spigot-093165d-ba575a5.
https://pastebin.com/0T78T7Jq

**Comment by EbonJaeger** [comment]
@liamcullins can you try the attached version of the plugin I posted a few comments up? The sooner I can get some verifications that it is indeed fixed, the sooner I can push out a release.

**Comment by kaniesha** [comment]
Sorry that I haven't updated you sooner - I've been waiting to see if it'd happen again but it hasn't. I'll try to force it (if it's still an issue) by switching my gamemode a few times.

**Comment by EbonJaeger** [comment]
@kaniesha switch to a GameMode or world where you have active potion effects. If it works, then we're all set.

**Comment by kaniesha** [comment]
Okay, I switched my gamemodes a bunch, threw potions, switched worlds, logged out, did all that. Inventory is still in tact properly!
