### ISSUE TITLE
Switching game modes causes huge console error. 

### ISSUE THREAD

**Issue by doomsdaymatrix** [EbonJaeger/perworldinventory-kt#148]
Using gms, gmsp, gmc, or gma (EssentialsX) causes huge error in console. 

**To Reproduce**
1. Open chat
2. Use a gamemode-switch command
4. Check console, see error

Expected no console error.

- [ 2.3.1] Using the latest released version of the plugin

Paper #107, 1.14.2. Occurs in 1.14.3 as well. 

https://pastebin.com/mUdtF0R2 Full error.

**Comment by EbonJaeger** [comment]
That error would seem to indicate that you somehow got items from a newer server version, then went to an older server version. Why that isn't supported by the server is beyond me, but that's beside the point.

What server version changes have you made recently (Paper builds, etc)? Did it work previously? This is all handled by the server itself, so I don't know that there's really anything I can actually do, but it would be good to at least pin down what change might have caused this to start happening.

**Comment by doomsdaymatrix** [comment]
Updated server version from 1.14.2 1.14.3 while it was still in it's early stages. Fixed by deleting pwi and reinstalling fresh, for either version. 

Thanks for the help!
