### ISSUE TITLE
Player Vaults?

### ISSUE THREAD

**Issue by ChiefReagan** [EbonJaeger/perworldinventory-kt#158]
Does this plugin work for player vaults?

**Comment by EbonJaeger** [comment]
I don't know. What are they?

**Comment by ChiefReagan** [comment]
https://www.spigotmc.org/resources/playervaultsx.51204/

**Comment by ChiefReagan** [comment]
@EbonJaeger

**Comment by EbonJaeger** [comment]
Looks like per-world vaults are something that developer will have to implement themselves (and it looks like it's already planned, or already existing, hard to tell from the description).
