### ISSUE TITLE
Outdated bStats Maven repository

### ISSUE THREAD

**Issue by stefvanschie** [EbonJaeger/perworldinventory-kt#170]
**Describe the bug**
In the pom.xml of this project, the old maven repository for bStats is used (http://repo.bstats.org/content/repositories/releases/). This repository is no longer available (gives a 521 when trying to access it) - instead a new Maven repository is available at the location https://repo.codemc.org/repository/maven-public (see https://bstats.org/getting-started/include-metrics). Because my plugin depends on this plugin, my continuous integration is failing, because the bStats location cannot be accessed.

**To Reproduce**
Try navigating to http://repo.bstats.org/content/repositories/releases/ and you should get a 521 error.

**Expected behavior**
Preferably, the new Maven repository location is used, so bStats can be found properly and my continuous integration no longer fails.

**Plugin version**
N/A

**Server version**
N/A

**Additional context and logs**
If preferred, I'm willing to fix this issue myself and make a pull request, just let me know if you'd like that.

**Comment by EbonJaeger** [comment]
Yeah, go ahead, thanks. It would have been nice if they had posted this on their site somewhere... :/
