### ISSUE TITLE
Bed respawning doesn't work.

### ISSUE THREAD

**Issue by frenchbones** [EbonJaeger/perworldinventory-kt#174]
**Describe the bug**
Bed respawn points does not work!

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a world
2. Sleep
4. Die
5. You will respawn at the world spawn, not your bed spawn.

**Expected behaviour**
Respawn next to the bed you slept in.

**Plugin version**
- [x] Using the version 2.3.1 of the plugin (latest)
- [x] Using `perworldinventory-kt-2.3.1` jar

**Server version**
paper-latest-1.15.jar

**Additional context and logs**
No errors in the log whatsoever.
I've attached my _config.yml_ and _worlds.yml_ down below:
[PWI Files.zip](https://github.com/EbonJaeger/perworldinventory-kt/files/4450256/PWI.Files.zip)

Thanks a lot!

**Comment by EbonJaeger** [comment]
Make sure the config option `manage-death-respawn` is set to `false`. If that doesn't do it, check Essentials and/or MultiVerse.

**Comment by frenchbones** [comment]
> Make sure the config option `manage-death-respawn` is set to `false`. If that doesn't do it, check Essentials and/or MultiVerse.
> 
> The logic though should be updated to take into account bed spawns...
> 
> **EDIT: You already have the config option set to false, so check Essentials and MultiVerse configs.

I know it is this plugin because when I remove it works normally...
