### ISSUE TITLE
Certain worlds aren't changing gamemode

### ISSUE THREAD

**Issue by 3nder1ord** [EbonJaeger/perworldinventory-kt#181]
I am using 1.14.4, newest released pwi version from spigot, and the following are my plugins and the configs i have:
![image](https://user-images.githubusercontent.com/42003312/80426934-c511f280-88b4-11ea-91b5-08d4cdfab994.png)
![image](https://user-images.githubusercontent.com/42003312/80427002-e377ee00-88b4-11ea-8294-7194696e5d50.png)
![image](https://user-images.githubusercontent.com/42003312/80427039-f12d7380-88b4-11ea-9983-cc0135e3eb10.png)
![image](https://user-images.githubusercontent.com/42003312/80427077-01455300-88b5-11ea-9f29-58aaedc158ec.png)

The problem i'm having is that only one of the four creative worlds ('testing') sets the player to creative mode. There is no error in the console when i restart. I couldn't find a solution for why these worlds arent working anywhere and this is the last thing i have left to try.

**Comment by EbonJaeger** [comment]
Most likely it's MultiVerse doing it. There is a permission to bypass its GameMode enforcements, but I can never remember what it is off the top of my head. I would try that.

**Comment by 3nder1ord** [comment]
I found a permission for multiverse called "mv.bypass.gamemode.WORLD_NAME"
So if i give players the permission "mv.bypass.gamemode.creative" or "mv.bypass.gamemode.creativeflat" then they should change into creative mode when they travel to the creative world? This permission seems to be OP so i should use this command only for the creative worlds? (I will have to test this later, when there are no players on my server)

On a side note, i did try removing my two multiverse plugins (core and portals) and the creative world was still not in creative mode. Is there possibly something else that is overriding pwi?

**Comment by EbonJaeger** [comment]
> "mv.bypass.gamemode.WORLD_NAME"

Yeah, that's the one. If you want PWI to manage gamemodes instead of MultiVerse, you'll have to set that on all worlds. That's just how MultiVerse works.

**Comment by 3nder1ord** [comment]
I added the permission "mv.bypass.gamemode.*" to the player and reloaded but the pwi still isnt working. I mentioned before that one of the worlds in my default-gamemode: CREATIVE is working. Why would only one of the four work? I checked to make sure that the worlds exist and are in the creative group so I cant think of why they wouldnt be working?

**Comment by 3nder1ord** [comment]
If you can't figure out a solution for this, i'm fine with closing this issue
