### ISSUE TITLE
[HELP] Somes bugs in PerWorldInventory

### ISSUE THREAD

**Issue by Junior007dj** [EbonJaeger/perworldinventory-kt#185]
Hello I propose a thing I am French and I do not use the translator!
(sorry for the faults)
Your plugin has 3 bugs to my knowledge, here they are:

- Header bugs, **java.lang.NoSuchFieldError: PLAYER_HEAD**

- Potion bug, **org.bukkit.potion.PotionEffect.hasIcon () Z**

- Bugs world, **Could not pass event PlayerChangedWorldEvent to PerWorldInventory v2.2.2**

Can you help me solve, I am ready to discuss in details!

Junior007, Fondatoria

**Comment by EbonJaeger** [comment]
I'm going to guess that you're not on Minecraft 1.13 or newer, in which case you have to use PerWorldInventory version 2.2.2, as older versions of Minecraft are no longer supported due to the multitude of changes in newer versions.

**Comment by Junior007dj** [comment]
Yeah !
Thank for this, I suposite already that ;)
If all of my bugs as repair, I give you 5 stars on spiggot !

And another think... in my separate world  I have a stuff in another world I have the same stuff but it's separate in config ! 
It's possible if you hav a error in PWC or it's me ?

**Comment by Junior007dj** [comment]
Hello @EbonJaeger can you help me for just one ?
Can you give me a link to a legacy fonctionnal PWI becaue I haved installed  the legacy version in 2.3.2 (server versions 1.11.2) and not work and I ahve already this bugs in up !

Help please !

**Comment by Junior007dj** [comment]
Thank @EbonJaeger I don't have any bug but the ollder lagacy versions is not fonctionnal (2.2.3 or 2.3.2, I don't no), I use the 2.2.2 legacy.

Fonctionnal, the bug of inventory think done! 

Very good support, I go to give you 5 Stars and sorry, I have take you time for a stupid issue!

Thank, have a good day!

**Comment by EbonJaeger** [comment]
I'm glad to hear that it is working! :)
