### ISSUE TITLE
com.google.gson.stream.MalformedJsonException: Unterminated string at line 1 column 24577

### ISSUE THREAD

**Issue by DardBrinza** [EbonJaeger/perworldinventory-kt#61]
Latest paper 1.12.2
https://pastebin.com/GXrvbrX4

**Comment by EbonJaeger** [comment]
GSON is no longer being used as of https://github.com/EbonJaeger/perworldinventory-kt/commit/ae721bd333239f8fd6e1608cc68bfa1e41469027. Open a new issue if this still persists with the new one.
