### ISSUE TITLE
unknown issue cause

### ISSUE THREAD

**Issue by BobbyMere** [EbonJaeger/perworldinventory-kt#76]
Whenever I leave the server with an item in hand, I get this 

```
01.09 12:33:08 [Server] INFO Saved the world
01.09 12:33:08 [Server] INFO Saving...
01.09 12:33:08 [Server] INFO Saving is already turned on
01.09 12:33:08 [Multicraft] Auto-saving world...
01.09 12:32:46 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
01.09 12:32:46 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
01.09 12:32:46 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
01.09 12:32:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.09 12:32:46 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.09 12:32:46 [Server] INFO at me.ebonjaeger.perworldinventory.service.BukkitService$sam$java_lang_Runnable$0.run(BukkitService.kt) ~[?:?]
01.09 12:32:46 [Server] INFO at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:20) ~[?:?]
01.09 12:32:46 [Server] INFO at me.ebonjaeger.perworldinventory.data.ProfileManager$addPlayerProfile$1.invoke(ProfileManager.kt:59) ~[?:?]
01.09 12:32:46 [Server] INFO at me.ebonjaeger.perworldinventory.data.FlatFile.savePlayer(FlatFile.kt:44) ~[?:?]
01.09 12:32:46 [Server] INFO at me.ebonjaeger.perworldinventory.serialization.PlayerSerializer.serialize(PlayerSerializer.kt:34) ~[?:?]
01.09 12:32:46 [Server] INFO at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeAllInventories(InventorySerializer.kt:23) ~[?:?]
01.09 12:32:46 [Server] INFO at me.ebonjaeger.perworldinventory.serialization.InventorySerializer.serializeInventory(InventorySerializer.kt:43) ~[?:?]
01.09 12:32:46 [Server] INFO at me.ebonjaeger.perworldinventory.serialization.ItemSerializer.serialize(ItemSerializer.kt:49) ~[?:?]
01.09 12:32:46 [Server] INFO java.lang.NoSuchFieldError: PLAYER_HEAD
01.09 12:32:46 [Server] WARN Plugin PerWorldInventory v2.1.0 generated an exception while executing task 62
01.09 12:32:46 [Server] INFO Ergenta left the game
01.09 12:32:46 [Disconnect] User Ergenta has disconnected, reason: Disconnected
```

I'm using perworldinventory-kt-2.1.0-legacy.jar and 1.12.1 spigot

**Comment by BobbyMere** [comment]
# In this file you define your groups and the worlds in them.
# Follow this format:
# groups:
#   default:
#     worlds:
#     - world
#     - world_nether
#     - world_the_end
#     default-gamemode: SURVIVAL
#   creative:
#     worlds:
#     - creative
#     default-gamemode: CREATIVE
#
# 'default' and 'creative' are the names of the groups
# worlds: is a list of all worlds in the group
# If you have 'manage-gamemodes' set to true in the main config, the server
# will use the 'default-gamemode' here to know what gamemode to put users in.
groups:
  default:
    worlds:
    - world
    - world_nether
    - world_the_end
    default-gamemode: SURVIVAL
   creative:
     worlds:
     - creative
     creative-gamemode: CREATIVE 

causes [code]01.09 12:03:10 [Multicraft] Skipped 33 lines due to rate limit (30/s)
01.09 12:03:06 [Server] INFO ^
01.09 12:03:06 [Server] INFO default:
01.09 12:03:06 [Server] INFO in 'string', line 20, column 3:
01.09 12:03:06 [Server] INFO Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
01.09 12:03:06 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
01.09 12:03:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_101]
01.09 12:03:06 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_101]
01.09 12:03:06 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.09 12:03:06 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.09 12:03:06 [Server] INFO at me.ebonjaeger.perworldinventory.service.BukkitService$sam$java_lang_Runnable$0.run(BukkitService.kt) [perworldinventory-kt-2.1.0.jar:?]
01.09 12:03:06 [Server] INFO at me.ebonjaeger.perworldinventory.GroupManager$loadGroups$1.invoke(GroupManager.kt:13) [perworldinventory-kt-2.1.0.jar:?]
01.09 12:03:06 [Server] INFO at me.ebonjaeger.perworldinventory.GroupManager$loadGroups$1.invoke(GroupManager.kt:110) [perworldinventory-kt-2.1.0.jar:?]
01.09 12:03:06 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) [spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.09 12:03:06 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.09 12:03:06 [Server] INFO at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.09 12:03:06 [Server] INFO at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[spigot-1.12.1-20170809a.jar:git-Spigot-5340a52-27b8bf9]
01.09 12:03:06 [Server] INFO ^
01.09 12:03:06 [Server] INFO creative:
01.09 12:03:06 [Server] INFO in 'string', line 26, column 4:
01.09 12:03:06 [Server] INFO expected <block end>, but found BlockMappingStart
01.09 12:03:06 [Server] INFO ^
01.09 12:03:06 [Server] INFO default:
01.09 12:03:06 [Server] INFO in 'string', line 20, column 3:
01.09 12:03:06 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while parsing a block mapping
01.09 12:03:06 [Server] ERROR Cannot load plugins/PerWorldInventory/worlds.yml[/code]

**Comment by EbonJaeger** [comment]
You are not using the legacy jar, the version in the log clearly says v2.1.0. If it was the legacy jar, it would read v2.1.0-legacy.
