### ISSUE TITLE
Relogging gamemode issue

### ISSUE THREAD

**Issue by iKordaR** [EbonJaeger/perworldinventory-kt#80]
When I set my gamemode to spectator, then relog or change dimension and then join the dimension I was spectator in, it puts me back into survival, anyone know how to fix this, it's annoying af.
Plugins (14) : CoreProtect, dynmap, OpenInv, DIYspy, PermissionsEx, PlayTime, ChatEx, PerWorldInventory, PlotSquared, GMC, Multiverse-Core, ProtocolLib, TreysCommandBlocker, SuperVanish

**Comment by EbonJaeger** [comment]
That's a MultiVerse thing. I always got around it by setting a bypass permission to everyone for MV. Can never remember what it is though.
