### ISSUE TITLE
Feature request to help combat the loss of inventories

### ISSUE THREAD

**Issue by Gnoarn** [EbonJaeger/perworldinventory-kt#99]
I would like to request inventory backups. it would be ideal that inventories be saved/backed up when a user logs out. this i think would partially help combat the random inventory loss. as well as a command to back up all user inventories and a command to restore all or one users inventory and settings..

**Comment by EbonJaeger** [comment]
Inventories *are* saved to the disk when players leave the server. Further "backups" don't actually combat any issues, nor are they PWI's responsibility.
